# Check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }} -X main.projectName={{ .ProjectName }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm
    # Path to main.go file or main package.
    # Default is `.`.
    main: ./cmd/docked/
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [ tar.gz ]
    format_overrides:
      - goos: windows
        formats: [ zip ]
    files:
      - LICENSE
      - README.md
sboms:
  - id: archive
    artifacts: archive
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - '^doc[s]?:'
      - '^\[doc[s]?\]'
      - '^[wW][iI][pP]:'
      - '^[tT][eE][sS][tT]:'

docker_digest:
  name_template: "digests.txt"
dockers_v2:
  - images:
      - "jimschubert/docked"
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "v{{ .Major }}"
    dockerfile: release.Dockerfile
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.name": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "https://github.com/jimschubert/docked"
      "org.opencontainers.image.licenses": "Apache-2.0"
    build_args:
      APP_NAME: "{{ .ProjectName }}"

#brews:
#  - repository:
#      owner: jimschubert
#      name: homebrew-tap
#      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
#    directory:  Formula
#    homepage:  https://github.com/jimschubert/docked
#    description: A Dockerfile linter
#    license: Apache 2.0
#    test: |
#      system "#{bin}/docked -v"
#    dependencies:
#      - name: go
#    install: |-
#      bin.install "docked"
