# Check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - go install golang.org/x/tools/cmd/stringer@v0.5.0
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }} -X main.projectName={{ .ProjectName }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
    # Path to main.go file or main package.
    # Default is `.`.
    main: ./cmd/docked/
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    rlcp: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - '^doc[s]?:'
      - '^\[doc[s]?\]'
      - '^[wW][iI][pP]:'
      - '^[tT][eE][sS][tT]:'
dockers:
  - goos: linux
    goarch: amd64
    use: buildx
    image_templates:
      - "jimschubert/{{ .ProjectName }}:latest"
      - "jimschubert/{{ .ProjectName }}:{{ .Tag }}"
      - "jimschubert/{{ .ProjectName }}:v{{ .Major }}"
      - "ghcr.io/jimschubert/{{ .ProjectName }}:latest"
      - "ghcr.io/jimschubert/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/jimschubert/{{ .ProjectName }}:v{{ .Major }}"

    dockerfile: release.Dockerfile

    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=jimschubert/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=A Dockerfile linter"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.url=https://github.com/jimschubert/docked"
      - "--platform=linux/amd64"

brews:
  - tap:
      owner: jimschubert
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/jimschubert/docked
    description: A Dockerfile linter
    license: Apache 2.0
    test: |
      system "#{bin}/docked -v"
    dependencies:
      - name: go
    install: |-
      bin.install "docked"
